using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HorseRaceCalculator
{
    internal static class HorsePool
    {
        public static Dictionary<string, byte> Initialize()
        {
            return new Dictionary<string, byte>
                {
                    { "A Tethered End", 27 },
                    { "Bad Egg", 29 },
                    { "Banana Hammock", 16 },
                    { "Better than Nothing", 15 },
                    { "Black Rock Rooster", 18 },
                    { "Bleet Me Baby", 7 },
                    { "Blue Dream", 2 },
                    { "Borrowed Sorrow", 12 },
                    { "Bouncy Blessed", 5 },
                    { "Cancelled Check", 25 },
                    { "Can't Be Wronger", 28 },
                    { "Clapback Charlie", 10 },
                    { "Constant Brag", 3 },
                    { "Country Stuck", 21 },
                    { "Crackers and Please", 3 },
                    { "Creepy Dentist", 7 },
                    { "Crock Janley", 8 },
                    { "Dancin' Pole", 9 },
                    { "Dancin' Shoes", 5 },
                    { "Darling Ricki", 22 },
                    { "Dead Fam", 26 },
                    { "Dead Heat Hattie", 17 },
                    { "Dexie Runner", 6 },
                    { "Divorced Doctor", 7 },
                    { "Doozy Floozy", 13 },
                    { "Downtown Renown", 4 },
                    { "Dr. Deez Reins", 5 },
                    { "Dream Shatterer", 1 },
                    { "Drone Warning", 8 },
                    { "Drunken Brandee", 14 },
                    { "Durban Poison", 20 },
                    { "Feed the Trolls", 30 },
                    { "Fire Hazards", 24 },
                    { "Flipped Wig", 12 },
                    { "Friendly Fire", 9 },
                    { "Getting Haughty", 3 },
                    { "Ghost Dank", 10 },
                    { "Glass or Tina", 23 },
                    { "Hard Time Done", 18 },
                    { "Hell for Weather", 2 },
                    { "Hennigan's Steed", 4 },
                    { "Hippie Crack", 23 },
                    { "Hot & Bothered", 2 },
                    { "Invade Grenade", 13 },
                    { "It's a Trap", 1 },
                    { "Kraff Running", 14 },
                    { "Lead Is out", 3 },
                    { "Lit as Truck", 1 },
                    { "Lonely Stepbrother", 3 },
                    { "Los Santos Savior", 5 },
                    { "Lover's Speed", 2 },
                    { "Measles Smeezles", 15 },
                    { "Micro Aggression", 8 },
                    { "Minimum Wager", 26 },
                    { "Miss Mary John", 22 },
                    { "Miss Triggered", 19 },
                    { "Mister Redacted", 19 },
                    { "Mister Scissors", 7 },
                    { "Money to Burn", 30 },
                    { "Moon Rocks", 4 },
                    { "Mr.Worthwhile", 2 },
                    { "Mud Dragon", 5 },
                    { "Night-time Mare", 16 },
                    { "Northern Lights", 15 },
                    { "Nuns Orders", 9 },
                    { "Ol' Skag", 28 },
                    { "Old Ill Will", 29 },
                    { "Omens and Ice", 3 },
                    { "Pedestrian", 25 },
                    { "Pretty as a Pistol", 4 },
                    { "Questionable Dignity", 12 },
                    { "Reach Around Town", 6 },
                    { "Robocall", 4 },
                    { "Salt 'n' Sauce", 1 },
                    { "Salty and Woke", 17 },
                    { "Scrawny Nag", 30 },
                    { "Sir Scrambled", 26 },
                    { "Sizzurp", 13 },
                    { "Snatched Your Mama", 1 },
                    { "Social Media Warrior", 27 },
                    { "Square to Go", 6 },
                    { "Study Buddy", 15 },
                    { "Stupid Money", 30 },
                    { "Sumptin Saucy", 1 },
                    { "Sweet Releaf", 4 },
                    { "Tax the Poor", 13 },
                    { "Tea Ache Sea", 24 },
                    { "Tenpenny", 10 },
                    { "There She Blows", 2 },
                    { "Throwing Shady", 21 },
                    { "Thunder Skunk", 20 },
                    { "Total Belter", 1 },
                    { "Turnt Mood", 12 },
                    { "Uptown Rider", 14 },
                    { "Wage of Consent", 21 },
                    { "Wee Scunner", 8 },
                    { "Worth a Kingdom", 2 },
                    { "Yay Yo Let's Go", 3 },
                    { "Yellow Sunshine", 5 }
                };
        }
    }
}
